#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

clearup ()
{
    rm -f "$tmp"
    rm -f /tmp/input.json
    rm -fr ~/.config/launchpad
}

trap clearup EXIT INT TERM

tmp=$(mktemp -u /tmp/json-XXXXXX)

exec 3>&1
exec 1>&2
jq -M -S . < /dev/stdin > /tmp/input.json

if [ "$(jq -r '.source | has("oauth_consumer_key")' < /tmp/input.json)" = 'true' ]; then
    oauth_consumer_key="$(jq -r .source.oauth_consumer_key < /tmp/input.json)"
else
    echo 'You need to provide the oauth_consumer_key.'
    exit 1
fi

if [ "$(jq -r '.source | has("oauth_token")' < /tmp/input.json)" = 'true' ]; then
    oauth_token="$(jq -r .source.oauth_token < /tmp/input.json)"
else
    echo 'You need to provide the oauth_token.'
    exit 1
fi

if [ "$(jq -r '.source | has("oauth_token_secret")' < /tmp/input.json)" = 'true' ]; then
    oauth_token_secret="$(jq -r .source.oauth_token_secret < /tmp/input.json)"
else
    echo 'You need to provide the oauth_token_secret.'
    exit 1
fi

mkdir -p ~/.config/launchpad
cat > ~/.config/launchpad/"$oauth_consumer_key" <<ENDLINE
#!/bin/bash

export oauth_token="${oauth_token}"
export oauth_token_secret="${oauth_token_secret}"
ENDLINE

if [ "$(jq -r '.source | has("id")' < /tmp/input.json)" = 'true' ]; then
    case "$(jq -r '.source.id | type' < /tmp/input.json)" in
        ('number')
            id=("$(jq -r .source.id < /tmp/input.json)")
            ;;
        ('array')
            mapfile -t id < <(jq -r '.source.id | .[]' < /tmp/input.json)
            ;;
        (*)
            echo "Invalid input for .source.id"
            exit 1
            ;;
    esac
else
    id=()
fi

if [ "$(jq -r '.source | has("status")' < /tmp/input.json)" = 'true' ]; then
    case "$(jq -r '.source.status | type' < /tmp/input.json)" in
        ('string')
            status=("$(jq -r .source.status < /tmp/input.json)")
            ;;
        ('array')
            mapfile -t status < <(jq -r '.source.status | .[]' < /tmp/input.json)
            ;;
        (*)
            echo "Invalid input for .source.status"
            exit 1
            ;;
    esac
else
    status=()
fi

if [ "$(jq -r '.source | has("project")' < /tmp/input.json)" = 'true' ]; then
    project="$(jq -r .source.project < /tmp/input.json)"
else
    project=''
fi

if [ "$(jq -r '.source | has("tag")' < /tmp/input.json)" = 'true' ]; then
    case "$(jq -r '.source.tag | type' < /tmp/input.json)" in
        ('number')
            tag=("$(jq -r '.source.tag' < /tmp/input.json)")
            ;;
        ('string')
            tag=("$(jq -r '.source.tag' < /tmp/input.json)")
            ;;
        ('array')
            mapfile -t tag < <(jq -r '.source.tag|.[]' < /tmp/input.json | sort)
            ;;
        (*)
            echo "Type '$(jq -r '.source.tag | type' < /tmp/input.json)' input is invalid for .source.tag"
            exit 1
            ;;
    esac
else
    tag=()
fi

if [ "$(jq -r '.source | has("modified_since")' < /tmp/input.json)" = 'true' ]; then
    modified_since="$(jq -r .source.modified_since < /tmp/input.json)"
else
    modified_since=''
fi

if [ "$(jq -r '.version | has("date_last_updated")' < /tmp/input.json)" = 'true' ]; then
    old_date_last_updated="$(jq -r '.version.date_last_updated' < /tmp/input.json)"
else
    old_date_last_updated=''
fi

if [ "$(jq -r '.version | has("modified_since")' < /tmp/input.json)" = 'true' ]; then
    old_modified_since="$(jq -r '.version.modified_since' < /tmp/input.json)"
else
    old_modified_since=''
fi

if [ "$(jq -r '.version | has("sha256")' < /tmp/input.json)" = 'true' ]; then
    sha256sum="$(jq -r '.version.sha256' < /tmp/input.json)"
else
    sha256sum=''
fi

case "$0" in
    ('/opt/resource/out')
        jq -n '{}' >&3
        exit
        ;;
    ('/opt/resource/in')
        cd "$1"
        mkdir tasks
        ;;
esac

declare -A etag=()
declare -A title=()
declare -a args=()

for name in "${tag[@]}"; do
    args+=("tags==$name")
done

if [ -n "${tag[*]}" ] && [ "$(jq -r '.source | has("combinator")' < /tmp/input.json)" = 'true' ]; then
    case "$(jq -r .source.combinator < /tmp/input.json)" in
        (all)
            args+=('tags_combinator==All')
            ;;
        (any)
            args+=('tags_combinator==Any')
            ;;
    esac
fi

if [ "$modified_since" = 'auto' ]; then
    if [ "$0" = /opt/resource/check ] && [ -n "$old_date_last_updated" ]; then
        args+=("modified_since==$old_date_last_updated")
    elif [ "$0" = /opt/resource/in ] && [ -n "$old_modified_since" ]; then
        args+=("modified_since==$old_modified_since")
    fi
elif [ -n "$modified_since" ]; then
    args+=("modified_since==$modified_since")
fi

for name in "${status[@]}"; do
    case "$name" in
        ("New"|"Incomplete"|"Opinion"|"Invalid"|"Won't Fix"|"Expired"|"Confirmed"|"Triaged"|"In Progress"|"Fix Committed"|"Fix Released"|"Unknown")
            args+=("status==$name")
            ;;
        (*)
            echo "$name is not a valid status."
            exit 1
            ;;
    esac
done

if [ -n "$project" ]; then
    echo launchpad-api get "$project" ws.op==searchTasks "${args[@]}"
    oauth_consumer_key="$oauth_consumer_key" launchpad-api get "$project" ws.op==searchTasks "${args[@]}" > "$tmp"

    while read -r bug_link; do
        id+=("$(basename "$bug_link")")
    done < <(jq -r '.entries | .[] | .bug_link' < "$tmp")
    echo -en "\rCollected ${#id[@]} IDs"

    next=$(jq -r .next_collection_link < "$tmp")
    while [ "$next" != 'null' ]; do
        http --ignore-stdin --check-status --follow "$next" > "$tmp"
        while read -r bug_link; do
            id+=("$(basename "$bug_link")")
        done < <(jq -r '.entries | .[] | .bug_link' < "$tmp")
        echo -en "\rCollected ${#id[@]} IDs"
        next=$(jq -r .next_collection_link < "$tmp")
    done
    echo ""
fi

if [ -z "${id[*]}" ]; then
    case "$0" in
        ('/opt/resource/check')
            if [ "$modified_since" = 'auto' ]; then
                json='[{"sha256":"'"$sha256sum"'","date_last_updated":"'"$old_date_last_updated"'","modified_since":"'"$old_modified_since"'"}]'
            else
                json='[{"sha256":"'"$sha256sum"'"}]'
            fi
            ;;
        ('/opt/resource/in')
            if [ "$modified_since" = 'auto' ]; then
                json='{"version":{"sha256":"'"$sha256sum"'","date_last_updated":"'"$old_date_last_updated"'","modified_since":"'"$old_modified_since"'"}}'
            else
                json='{"version":{"sha256":"'"$sha256sum"'"}}'
            fi
            ;;
    esac
    jq -n "$json" >&3
    exit
fi

mapfile -t bugs < <(sort -u -n <<<"${id[*]}")

if [ "$modified_since" = 'auto' ]; then
    if [ -n "$old_date_last_updated" ]; then
        new_modified_since="$old_date_last_updated"
    else
        new_modified_since=''
    fi
fi

new_date_last_updated=''
for idx in "${!bugs[@]}"; do
    echo -en "\rFetching $((idx + 1))/${#bugs[@]} IDs"
    bug="${bugs[$idx]}"
    oauth_consumer_key="$oauth_consumer_key" launchpad-api get bugs/"$bug" > "$bug".json
    etag[$bug]=$(jq -r .http_etag < "$bug".json)
    title[$bug]=$(jq -r .title < "$bug".json | sed -e 's/\\/\\\\/g' -e 's/\"/\\\"/g')
    if [ "$modified_since" = 'auto' ]; then
        last_updated="$(jq -r .date_last_updated < "$bug".json)"
        if [[ "$last_updated" > "$new_date_last_updated" ]]; then
            new_date_last_updated="$last_updated"
        fi
    fi
    if [ -d tasks ]; then
        oauth_consumer_key="$oauth_consumer_key" launchpad-api get bugs/"$bug"/bug_tasks > tasks/"$bug".json
    fi
done

sha256sum="$(echo "${id[@]}" "${etag[@]}" | sha256sum | awk '{print $1}')"

case "$0" in
    ('/opt/resource/check')
        if [ "$modified_since" = 'auto' ]; then
            json='[{"sha256":"'"$sha256sum"'","date_last_updated":"'"$new_date_last_updated"'","modified_since":"'"$new_modified_since"'"}]'
        else
            json='[{"sha256":"'"$sha256sum"'"}]'
        fi
        ;;
    ('/opt/resource/in')
        if [ "$modified_since" = 'auto' ]; then
            json='{"version":{"sha256":"'"$sha256sum"'","date_last_updated":"'"$new_date_last_updated"'","modified_since":"'"$old_modified_since"'"},"metadata":['
        else
            json='{"version":{"sha256":"'"$sha256sum"'"},"metadata":['
        fi
        metadata=()
        for bug in "${bugs[@]}"; do
            metadata+=('{"name":"'"$bug"'","value":"'"${title[$bug]}"'"}')
        done
        IFS=,
        json+="${metadata[*]}"']}'
        ;;
esac

echo "$json" > "$tmp"
sed -i 's/\t/ /g' "$tmp"
jq -n --slurpfile all "$tmp" '$all[0]' >&3
